const { PrismaClient } = require('@prisma/client')
const bcrypt = require('bcryptjs')

const prisma = new PrismaClient()

async function main() {
  console.log('Seeding database...')

  // Create admin account
  const hashedPassword = await bcrypt.hash('admin123', 10)

  const admin = await prisma.user.upsert({
    where: { mobile: '9958636753' },
    update: {},
    create: {
      mobile: '9958636753',
      email: 'sanjeevcs44@gmail.com',
      password: hashedPassword,
      firstName: 'Sanjeev',
      lastName: 'Sharma',
      fatherOrHusbandName: 'N/A',
      age: 30,
      gender: 'Male',
      role: 'ADMIN',
      approvalStatus: 'APPROVED',
      isFirstLogin: false,
      state: 'Rajasthan',
      district: 'Jaipur',
      currentAddress: 'Jaipur, Rajasthan',
      ancestralVillage: 'Jaipur',
      gotra: 'Sharma',
      education: 'Engineering',
      profession: 'Software Developer',
      bio: 'Super Admin - Can manage all users and moderators',
    },
  })

  console.log('✅ Admin created:', admin.firstName, admin.lastName)
  console.log('📧 Email:', admin.email)
  console.log('📱 Mobile:', admin.mobile)
  console.log('🔑 Password: admin123')

  // Create dummy users with complete registration form data
  const dummyUsers = [
    {
      mobile: '9876543210',
      email: 'priya.gautam@matrimonial.com',
      password: await bcrypt.hash('password123', 10),
      firstName: 'Priya',
      lastName: 'Sharma',
      fatherOrHusbandName: 'Rajesh Sharma',
      motherName: 'Sunita Devi',
      maritalStatus: 'UNMARRIED',
      age: 26,
      dateOfBirth: new Date('1999-03-15'),
      gender: 'Female',
      role: 'USER',
      approvalStatus: 'APPROVED',
      isFirstLogin: false,
      state: 'मध्यप्रदेश',
      district: 'भिंड',
      currentAddress: 'Main Road, Bhind, MP',
      ancestralVillage: 'akoda-अकोड़ा',
      education: '12वीं',
      profession: 'गृह कार्य',
      gotra: 'gautam-गौतम',
      motherGotra: 'bharadwaj-भारद्वाज',
      yearlyIncome: '2-5 लाख',
    },
    {
      mobile: '9876543211',
      email: 'rahul.bharadwaj@matrimonial.com',
      password: await bcrypt.hash('password123', 10),
      firstName: 'Rahul',
      lastName: 'Kumar',
      fatherOrHusbandName: 'Suresh Kumar',
      motherName: 'Kamla Devi',
      maritalStatus: 'UNMARRIED',
      age: 28,
      dateOfBirth: new Date('1997-07-22'),
      gender: 'Male',
      role: 'USER',
      approvalStatus: 'APPROVED',
      isFirstLogin: false,
      state: 'मध्यप्रदेश',
      district: 'ग्वालियर',
      currentAddress: 'Lashkar, Gwalior, MP',
      ancestralVillage: 'charathar-चरथर',
      education: 'B.Tech',
      profession: 'शासकीय सेवा',
      gotra: 'bharadwaj-भारद्वाज',
      motherGotra: 'gautam-गौतम',
      yearlyIncome: '5-10 लाख',
    },
    {
      mobile: '9876543212',
      email: 'anjali.mudgal@matrimonial.com',
      password: await bcrypt.hash('password123', 10),
      firstName: 'Anjali',
      lastName: 'Patel',
      fatherOrHusbandName: 'Ramesh Patel',
      motherName: 'Geeta Devi',
      maritalStatus: 'UNMARRIED',
      age: 24,
      dateOfBirth: new Date('2001-11-10'),
      gender: 'Female',
      role: 'USER',
      approvalStatus: 'APPROVED',
      isFirstLogin: false,
      state: 'उत्तरप्रदेश',
      district: 'आगरा',
      currentAddress: 'Taj Ganj, Agra, UP',
      ancestralVillage: 'jamna-जामना',
      education: 'B.Sc',
      profession: 'शिक्षण कार्य',
      gotra: 'mudgal-मुद्गल',
      motherGotra: 'parashar-पाराशर',
      yearlyIncome: '3-5 लाख',
    },
    {
      mobile: '9876543213',
      email: 'vikram.parashar@matrimonial.com',
      password: await bcrypt.hash('password123', 10),
      firstName: 'Vikram',
      lastName: 'Singh',
      fatherOrHusbandName: 'Mahendra Singh',
      motherName: 'Anita Devi',
      maritalStatus: 'MARRIED',
      age: 32,
      dateOfBirth: new Date('1993-05-18'),
      gender: 'Male',
      role: 'MODERATOR',
      approvalStatus: 'APPROVED',
      isFirstLogin: false,
      assignedVillage: 'virdhanpura-विर्धनपुरा',
      state: 'राजस्थान',
      district: 'जयपुर',
      currentAddress: 'Vaishali Nagar, Jaipur, RJ',
      ancestralVillage: 'virdhanpura-विर्धनपुरा',
      education: 'M.A',
      profession: 'समाज सेवा',
      gotra: 'parashar-पाराशर',
      motherGotra: 'choube-चौबे',
      yearlyIncome: '10+ लाख',
    },
    {
      mobile: '9876543214',
      email: 'meera.choube@matrimonial.com',
      password: await bcrypt.hash('password123', 10),
      firstName: 'Meera',
      lastName: 'Joshi',
      fatherOrHusbandName: 'Prakash Joshi',
      motherName: 'Radha Devi',
      maritalStatus: 'UNMARRIED',
      age: 25,
      dateOfBirth: new Date('2000-09-03'),
      gender: 'Female',
      role: 'USER',
      approvalStatus: 'APPROVED',
      isFirstLogin: false,
      state: 'उत्तरप्रदेश',
      district: 'कानपुर नगर',
      currentAddress: 'Civil Lines, Kanpur, UP',
      ancestralVillage: 'daboha-दबोहा',
      education: 'B.Com',
      profession: 'बैंकिंग सेक्टर',
      gotra: 'choube-चौबे',
      motherGotra: 'dikshit-दीक्षित',
      yearlyIncome: '4-7 लाख',
    },
    {
      mobile: '9876543215',
      email: 'arjun.birthariya@matrimonial.com',
      password: await bcrypt.hash('password123', 10),
      firstName: 'Arjun',
      lastName: 'Chauhan',
      fatherOrHusbandName: 'Vikrant Chauhan',
      motherName: 'Savita Devi',
      maritalStatus: 'UNMARRIED',
      age: 30,
      dateOfBirth: new Date('1995-12-25'),
      gender: 'Male',
      role: 'USER',
      approvalStatus: 'APPROVED',
      isFirstLogin: false,
      state: 'मध्यप्रदेश',
      district: 'सागर',
      currentAddress: 'University Area, Sagar, MP',
      ancestralVillage: 'phoop-फूप',
      education: 'B.E/B.Tech',
      profession: 'प्राइवेट सेक्टर',
      gotra: 'birthariya-बिरथरिया',
      motherGotra: 'singhechiya-सिंघेचिया',
      yearlyIncome: '6-9 लाख',
    },
    {
      mobile: '9876543216',
      email: 'kavita.singhechiya@matrimonial.com',
      password: await bcrypt.hash('password123', 10),
      firstName: 'Kavita',
      lastName: 'Sharma',
      fatherOrHusbandName: 'Dinesh Sharma',
      motherName: 'Pushpa Devi',
      maritalStatus: 'MARRIED',
      age: 29,
      dateOfBirth: new Date('1996-04-08'),
      gender: 'Female',
      role: 'MODERATOR',
      approvalStatus: 'APPROVED',
      isFirstLogin: false,
      assignedVillage: 'pali-पाली',
      state: 'राजस्थान',
      district: 'सीकर',
      currentAddress: 'Civil Lines, Sikar, RJ',
      ancestralVillage: 'pali-पाली',
      education: 'M.A',
      profession: 'शिक्षण कार्य',
      gotra: 'singhechiya-सिंघेचिया',
      motherGotra: 'pachauri-पचौरी',
      yearlyIncome: '5-8 लाख',
    },
    {
      mobile: '9876543217',
      email: 'rohit.pachauri@matrimonial.com',
      password: await bcrypt.hash('password123', 10),
      firstName: 'Rohit',
      lastName: 'Kumar',
      fatherOrHusbandName: 'Ashok Kumar',
      motherName: 'Shanti Devi',
      maritalStatus: 'UNMARRIED',
      age: 27,
      dateOfBirth: new Date('1998-08-14'),
      gender: 'Male',
      role: 'USER',
      approvalStatus: 'APPROVED',
      isFirstLogin: false,
      state: 'मध्यप्रदेश',
      district: 'इंदौर',
      currentAddress: 'Vijay Nagar, Indore, MP',
      ancestralVillage: 'bhimpura-भीमपुरा',
      education: 'M.B.B.S',
      profession: 'चिकित्सा कार्य',
      gotra: 'pachauri-पचौरी',
      motherGotra: 'dube-दुबे',
      yearlyIncome: '10+ लाख',
    },
    {
      mobile: '9876543218',
      email: 'pooja.dikshit@matrimonial.com',
      password: await bcrypt.hash('password123', 10),
      firstName: 'Pooja',
      lastName: 'Gupta',
      fatherOrHusbandName: 'Anil Gupta',
      motherName: 'Meena Devi',
      maritalStatus: 'UNMARRIED',
      age: 23,
      dateOfBirth: new Date('2002-01-20'),
      gender: 'Female',
      role: 'USER',
      approvalStatus: 'APPROVED',
      isFirstLogin: false,
      state: 'उत्तरप्रदेश',
      district: 'अलीगढ़',
      currentAddress: 'Civil Lines, Aligarh, UP',
      ancestralVillage: 'sakraya-सकराया',
      education: 'ग्रेजुएट',
      profession: 'गृह कार्य',
      gotra: 'dikshit-दीक्षित',
      motherGotra: 'joshi-जोशी',
      yearlyIncome: '2-4 लाख',
    },
    {
      mobile: '9876543219',
      email: 'amit.dube@matrimonial.com',
      password: await bcrypt.hash('password123', 10),
      firstName: 'Amit',
      lastName: 'Kumar',
      fatherOrHusbandName: 'Ravi Kumar',
      motherName: 'Sita Devi',
      maritalStatus: 'UNMARRIED',
      age: 35,
      dateOfBirth: new Date('1990-06-30'),
      gender: 'Male',
      role: 'USER',
      approvalStatus: 'APPROVED',
      isFirstLogin: false,
      state: 'मध्यप्रदेश',
      district: 'भिंड',
      currentAddress: 'Market Area, Bhind, MP',
      ancestralVillage: 'mehgaon-मेहगांव',
      education: 'B.Com',
      profession: 'व्यापारी',
      gotra: 'dube-दुबे',
      motherGotra: 'rawat-रावत',
      yearlyIncome: '8-12 लाख',
    },
    {
      mobile: '9876543220',
      email: 'suresh.joshi@matrimonial.com',
      password: await bcrypt.hash('password123', 10),
      firstName: 'Suresh',
      lastName: 'Prasad',
      fatherOrHusbandName: 'Ram Prasad',
      motherName: 'Kalawati Devi',
      maritalStatus: 'UNMARRIED',
      age: 31,
      dateOfBirth: new Date('1994-02-10'),
      gender: 'Male',
      role: 'USER',
      approvalStatus: 'APPROVED',
      isFirstLogin: false,
      state: 'मध्यप्रदेश',
      district: 'मुरैना',
      currentAddress: 'Village Area, Morena, MP',
      ancestralVillage: 'imliya-इमलिया',
      education: '12वीं',
      profession: 'कृषि कार्य',
      gotra: 'joshi-जोशी',
      motherGotra: 'saavran-सावरण',
      yearlyIncome: '3-5 लाख',
    },
    {
      mobile: '9876543221',
      email: 'ravi.rawat@matrimonial.com',
      password: await bcrypt.hash('password123', 10),
      firstName: 'Ravi',
      lastName: 'Tiwari',
      fatherOrHusbandName: 'Kamal Tiwari',
      motherName: 'Urmila Devi',
      maritalStatus: 'UNMARRIED',
      age: 29,
      dateOfBirth: new Date('1996-07-05'),
      gender: 'Male',
      role: 'USER',
      approvalStatus: 'APPROVED',
      isFirstLogin: false,
      state: 'उत्तरप्रदेश',
      district: 'आगरा',
      currentAddress: 'Sikandra, Agra, UP',
      ancestralVillage: 'gurjakapura-गुर्जाकापुरा',
      education: 'B.A',
      profession: 'शासकीय सेवा',
      gotra: 'rawat-रावत',
      motherGotra: 'ghritkul-घृतकुल',
      yearlyIncome: '4-6 लाख',
    },
    {
      mobile: '9876543222',
      email: 'sunita.saavran@matrimonial.com',
      password: await bcrypt.hash('password123', 10),
      firstName: 'Sunita',
      lastName: 'Sharma',
      fatherOrHusbandName: 'Devendra Sharma',
      motherName: 'Laxmi Devi',
      maritalStatus: 'UNMARRIED',
      age: 26,
      dateOfBirth: new Date('1999-04-18'),
      gender: 'Female',
      role: 'USER',
      approvalStatus: 'APPROVED',
      isFirstLogin: false,
      state: 'मध्यप्रदेश',
      district: 'ग्वालियर',
      currentAddress: 'Hospital Road, Gwalior, MP',
      ancestralVillage: 'birgawan-बिरगवाँ',
      education: 'B.Sc.Nursing',
      profession: 'नर्सिंग',
      gotra: 'saavran-सावरण',
      motherGotra: 'upadhyay-उपाध्याय',
      yearlyIncome: '3-6 लाख',
    },
    {
      mobile: '9876543223',
      email: 'deepak.ghritkul@matrimonial.com',
      password: await bcrypt.hash('password123', 10),
      firstName: 'Deepak',
      lastName: 'Mohan',
      fatherOrHusbandName: 'Brij Mohan',
      motherName: 'Kiran Devi',
      maritalStatus: 'UNMARRIED',
      age: 32,
      dateOfBirth: new Date('1993-09-12'),
      gender: 'Male',
      role: 'USER',
      approvalStatus: 'APPROVED',
      isFirstLogin: false,
      state: 'उत्तरप्रदेश',
      district: 'अलीगढ़',
      currentAddress: 'Court Road, Aligarh, UP',
      ancestralVillage: 'simar-सिमार',
      education: 'L.L.B',
      profession: 'वकालत',
      gotra: 'ghritkul-घृतकुल',
      motherGotra: 'mukharaiya-मुखरैया',
      yearlyIncome: '7-10 लाख',
    },
    {
      mobile: '9876543224',
      email: 'neha.upadhyay@matrimonial.com',
      password: await bcrypt.hash('password123', 10),
      firstName: 'Neha',
      lastName: 'Mishra',
      fatherOrHusbandName: 'Rajendra Mishra',
      motherName: 'Saraswati Devi',
      maritalStatus: 'UNMARRIED',
      age: 27,
      dateOfBirth: new Date('1998-11-25'),
      gender: 'Female',
      role: 'USER',
      approvalStatus: 'APPROVED',
      isFirstLogin: false,
      state: 'मध्यप्रदेश',
      district: 'मुरैना',
      currentAddress: 'College Area, Morena, MP',
      ancestralVillage: 'kairora-कैरोरा',
      education: 'पोस्ट ग्रेजुएट',
      profession: 'शिक्षण कार्य',
      gotra: 'upadhyay-उपाध्याय',
      motherGotra: 'shrotriya-श्रोत्रिय(सोती)',
      yearlyIncome: '5-8 लाख',
    },
    {
      mobile: '9876543225',
      email: 'manish.mukharaiya@matrimonial.com',
      password: await bcrypt.hash('password123', 10),
      firstName: 'Manish',
      lastName: 'Shankar',
      fatherOrHusbandName: 'Hari Shankar',
      motherName: 'Parvati Devi',
      maritalStatus: 'UNMARRIED',
      age: 33,
      dateOfBirth: new Date('1992-03-08'),
      gender: 'Male',
      role: 'USER',
      approvalStatus: 'APPROVED',
      isFirstLogin: false,
      state: 'मध्यप्रदेश',
      district: 'भिंड',
      currentAddress: 'Industrial Area, Bhind, MP',
      ancestralVillage: 'daipura-दैपुरा',
      education: 'M.B.A',
      profession: 'मैनेजमेंट',
      gotra: 'mukharaiya-मुखरैया',
      motherGotra: 'kashyap-कश्यप',
      yearlyIncome: '10+ लाख',
    },
    {
      mobile: '9876543226',
      email: 'shalini.shrotriya@matrimonial.com',
      password: await bcrypt.hash('password123', 10),
      firstName: 'Shalini',
      lastName: 'Das',
      fatherOrHusbandName: 'Gopal Das',
      motherName: 'Rani Devi',
      maritalStatus: 'UNMARRIED',
      age: 24,
      dateOfBirth: new Date('2001-06-14'),
      gender: 'Female',
      role: 'USER',
      approvalStatus: 'APPROVED',
      isFirstLogin: false,
      state: 'उत्तरप्रदेश',
      district: 'आगरा',
      currentAddress: 'Shahganj, Agra, UP',
      ancestralVillage: 'gingarkhi-गिंगरखी',
      education: 'ग्रेजुएट',
      profession: 'गृह कार्य',
      gotra: 'shrotriya-श्रोत्रिय(सोती)',
      motherGotra: 'sanedhiya-सनेधिया',
      yearlyIncome: '2-4 लाख',
    },
    {
      mobile: '9876543227',
      email: 'vijay.kashyap@matrimonial.com',
      password: await bcrypt.hash('password123', 10),
      firstName: 'Vijay',
      lastName: 'Prakash',
      fatherOrHusbandName: 'Om Prakash',
      motherName: 'Shobha Devi',
      maritalStatus: 'UNMARRIED',
      age: 30,
      dateOfBirth: new Date('1995-02-28'),
      gender: 'Male',
      role: 'USER',
      approvalStatus: 'APPROVED',
      isFirstLogin: false,
      state: 'मध्यप्रदेश',
      district: 'ग्वालियर',
      currentAddress: 'Police Line, Gwalior, MP',
      ancestralVillage: 'manikpura-मानिकपुरा',
      education: 'ग्रेजुएट',
      profession: 'पुलिस सेवा',
      gotra: 'kashyap-कश्यप',
      motherGotra: 'dhamole-ढमोले',
      yearlyIncome: '6-9 लाख',
    },
    {
      mobile: '9876543228',
      email: 'rekha.sanedhiya@matrimonial.com',
      password: await bcrypt.hash('password123', 10),
      firstName: 'Rekha',
      lastName: 'Kumar',
      fatherOrHusbandName: 'Mahesh Kumar',
      motherName: 'Usha Devi',
      maritalStatus: 'UNMARRIED',
      age: 25,
      dateOfBirth: new Date('2000-08-05'),
      gender: 'Female',
      role: 'USER',
      approvalStatus: 'APPROVED',
      isFirstLogin: false,
      state: 'उत्तरप्रदेश',
      district: 'अलीगढ़',
      currentAddress: 'Medical Road, Aligarh, UP',
      ancestralVillage: 'chapra-चपरा',
      education: 'B.Pharma',
      profession: 'फार्मा सेक्टर',
      gotra: 'sanedhiya-सनेधिया',
      motherGotra: 'singholia-सिंघौलिया',
      yearlyIncome: '4-6 लाख',
    },
    {
      mobile: '9876543229',
      email: 'anil.dhamole@matrimonial.com',
      password: await bcrypt.hash('password123', 10),
      firstName: 'Anil',
      lastName: 'Lal',
      fatherOrHusbandName: 'Shyam Lal',
      motherName: 'Kamla Devi',
      maritalStatus: 'UNMARRIED',
      age: 28,
      dateOfBirth: new Date('1997-10-19'),
      gender: 'Male',
      role: 'USER',
      approvalStatus: 'APPROVED',
      isFirstLogin: false,
      state: 'मध्यप्रदेश',
      district: 'मुरैना',
      currentAddress: 'School Area, Morena, MP',
      ancestralVillage: 'gohad-गोहद',
      education: 'B.Ed',
      profession: 'शिक्षण कार्य',
      gotra: 'dhamole-ढमोले',
      motherGotra: 'tiwari-तिवारी',
      yearlyIncome: '3-5 लाख',
    },
    {
      mobile: '9876543230',
      email: 'priti.singholia@matrimonial.com',
      password: await bcrypt.hash('password123', 10),
      firstName: 'Priti',
      lastName: 'Sharma',
      fatherOrHusbandName: 'Brijesh Sharma',
      motherName: 'Anita Devi',
      maritalStatus: 'UNMARRIED',
      age: 22,
      dateOfBirth: new Date('2003-12-01'),
      gender: 'Female',
      role: 'USER',
      approvalStatus: 'APPROVED',
      isFirstLogin: false,
      state: 'मध्यप्रदेश',
      district: 'भिंड',
      currentAddress: 'Nehru Nagar, Bhind, MP',
      ancestralVillage: 'gohadchauraha-गोहदचौराहा',
      education: '12वीं',
      profession: 'गृह कार्य',
      gotra: 'singholia-सिंघौलिया',
      motherGotra: 'madr-माद्र',
      yearlyIncome: '2-3 लाख',
    },
    {
      mobile: '9876543231',
      email: 'rajesh.tiwari@matrimonial.com',
      password: await bcrypt.hash('password123', 10),
      firstName: 'Rajesh',
      lastName: 'Prasad',
      fatherOrHusbandName: 'Rameshwar Prasad',
      motherName: 'Savitri Devi',
      maritalStatus: 'UNMARRIED',
      age: 34,
      dateOfBirth: new Date('1991-05-15'),
      gender: 'Male',
      role: 'USER',
      approvalStatus: 'APPROVED',
      isFirstLogin: false,
      state: 'उत्तरप्रदेश',
      district: 'आगरा',
      currentAddress: 'Kamla Nagar, Agra, UP',
      ancestralVillage: 'badagar-बड़ागर',
      education: 'Diploma',
      profession: 'कांट्रेक्टर शिप',
      gotra: 'tiwari-तिवारी',
      motherGotra: 'sagoriya-सागौरिया',
      yearlyIncome: '10+ लाख',
    },
    {
      mobile: '9876543232',
      email: 'sapna.madr@matrimonial.com',
      password: await bcrypt.hash('password123', 10),
      firstName: 'Sapna',
      lastName: 'Chandra',
      fatherOrHusbandName: 'Dinesh Chandra',
      motherName: 'Rekha Devi',
      maritalStatus: 'UNMARRIED',
      age: 26,
      dateOfBirth: new Date('1999-07-22'),
      gender: 'Female',
      role: 'USER',
      approvalStatus: 'APPROVED',
      isFirstLogin: false,
      state: 'मध्यप्रदेश',
      district: 'ग्वालियर',
      currentAddress: 'City Center, Gwalior, MP',
      ancestralVillage: 'ramanpura-रमनपुरा',
      education: 'B.Ed',
      profession: 'शिक्षण कार्य',
      gotra: 'madr-माद्र',
      motherGotra: 'sadwariya-सड़वारिया',
      yearlyIncome: '4-6 लाख',
    },
    {
      mobile: '9876543233',
      email: 'mohit.sagoriya@matrimonial.com',
      password: await bcrypt.hash('password123', 10),
      firstName: 'Mohit',
      lastName: 'Kumar',
      fatherOrHusbandName: 'Krishan Kumar',
      motherName: 'Suman Devi',
      maritalStatus: 'UNMARRIED',
      age: 29,
      dateOfBirth: new Date('1996-09-30'),
      gender: 'Male',
      role: 'USER',
      approvalStatus: 'APPROVED',
      isFirstLogin: false,
      state: 'मध्यप्रदेश',
      district: 'मुरैना',
      currentAddress: 'New Colony, Morena, MP',
      ancestralVillage: 'sirsauda-सिरसौदा',
      education: 'B.E/B.Tech',
      profession: 'प्राइवेट सेक्टर',
      gotra: 'sagoriya-सागौरिया',
      motherGotra: 'digharautiya-दिघरौतिया',
      yearlyIncome: '7-10 लाख',
    },
    {
      mobile: '9876543234',
      email: 'anita.sadwariya@matrimonial.com',
      password: await bcrypt.hash('password123', 10),
      firstName: 'Anita',
      lastName: 'Verma',
      fatherOrHusbandName: 'Mukesh Verma',
      motherName: 'Pushpa Devi',
      maritalStatus: 'UNMARRIED',
      age: 23,
      dateOfBirth: new Date('2002-04-10'),
      gender: 'Female',
      role: 'USER',
      approvalStatus: 'APPROVED',
      isFirstLogin: false,
      state: 'उत्तरप्रदेश',
      district: 'अलीगढ़',
      currentAddress: 'Gandhi Nagar, Aligarh, UP',
      ancestralVillage: 'bagulari-बगुलरी',
      education: 'ग्रेजुएट',
      profession: 'गृह कार्य',
      gotra: 'sadwariya-सड़वारिया',
      motherGotra: 'kudareeha-कुड.रिहा',
      yearlyIncome: '2-4 लाख',
    },
    {
      mobile: '9876543235',
      email: 'sandeep.digharautiya@matrimonial.com',
      password: await bcrypt.hash('password123', 10),
      firstName: 'Sandeep',
      lastName: 'Kumar',
      fatherOrHusbandName: 'Naresh Kumar',
      motherName: 'Sudha Devi',
      maritalStatus: 'UNMARRIED',
      age: 31,
      dateOfBirth: new Date('1994-11-18'),
      gender: 'Male',
      role: 'USER',
      approvalStatus: 'APPROVED',
      isFirstLogin: false,
      state: 'मध्यप्रदेश',
      district: 'भिंड',
      currentAddress: 'Bank Road, Bhind, MP',
      ancestralVillage: 'khurd-खुर्द',
      education: 'M.Com',
      profession: 'बैंकिंग सेक्टर',
      gotra: 'digharautiya-दिघरौतिया',
      motherGotra: 'beeribar-बेरीबार',
      yearlyIncome: '6-8 लाख',
    },
    {
      mobile: '9876543236',
      email: 'kavita.kudareeha@matrimonial.com',
      password: await bcrypt.hash('password123', 10),
      firstName: 'Kavita',
      lastName: 'Sharma',
      fatherOrHusbandName: 'Sunil Sharma',
      motherName: 'Maya Devi',
      maritalStatus: 'UNMARRIED',
      age: 28,
      dateOfBirth: new Date('1997-03-25'),
      gender: 'Female',
      role: 'USER',
      approvalStatus: 'APPROVED',
      isFirstLogin: false,
      state: 'मध्यप्रदेश',
      district: 'ग्वालियर',
      currentAddress: 'Medical College, Gwalior, MP',
      ancestralVillage: 'kheriya-खेरिया',
      education: 'M.B.B.S',
      profession: 'चिकित्सा कार्य',
      gotra: 'kudareeha-कुड.रिहा',
      motherGotra: 'patuliha-पटुलिहा',
      yearlyIncome: '10+ लाख',
    },
    // Additional users with overlapping gotras for testing
    {
      mobile: '9876543228',
      email: 'amit.gautam@matrimonial.com',
      password: await bcrypt.hash('password123', 10),
      firstName: 'Amit',
      lastName: 'Mishra',
      fatherOrHusbandName: 'Ramesh Mishra',
      motherName: 'Geeta Devi',
      maritalStatus: 'UNMARRIED',
      age: 29,
      dateOfBirth: new Date('1996-05-10'),
      gender: 'Male',
      role: 'USER',
      approvalStatus: 'APPROVED',
      isFirstLogin: false,
      state: 'मध्यप्रदेश',
      district: 'भिंड',
      currentAddress: 'Civil Lines, Bhind, MP',
      ancestralVillage: 'mahua-महुआ',
      education: 'B.A.',
      profession: 'निजी कार्य',
      gotra: 'gautam-गौतम', // Same as Priya
      motherGotra: 'mudgal-मुद्गल',
      yearlyIncome: '2-5 लाख',
    },
    {
      mobile: '9876543229',
      email: 'ritu.bharadwaj@matrimonial.com',
      password: await bcrypt.hash('password123', 10),
      firstName: 'Ritu',
      lastName: 'Tiwari',
      fatherOrHusbandName: 'Mahesh Tiwari',
      motherName: 'Savita Devi',
      maritalStatus: 'UNMARRIED',
      age: 24,
      dateOfBirth: new Date('2001-08-18'),
      gender: 'Female',
      role: 'USER',
      approvalStatus: 'APPROVED',
      isFirstLogin: false,
      state: 'उत्तरप्रदेश',
      district: 'आगरा',
      currentAddress: 'Sikandra, Agra, UP',
      ancestralVillage: 'barhan-बड़हन',
      education: 'B.Sc.',
      profession: 'गृह कार्य',
      gotra: 'bharadwaj-भारद्वाज', // Same as Rahul
      motherGotra: 'parashar-पाराशर',
      yearlyIncome: '2-5 लाख',
    },
    {
      mobile: '9876543230',
      email: 'vivek.mudgal@matrimonial.com',
      password: await bcrypt.hash('password123', 10),
      firstName: 'Vivek',
      lastName: 'Dubey',
      fatherOrHusbandName: 'Ramkumar Dubey',
      motherName: 'Laxmi Devi',
      maritalStatus: 'UNMARRIED',
      age: 30,
      dateOfBirth: new Date('1995-11-05'),
      gender: 'Male',
      role: 'USER',
      approvalStatus: 'APPROVED',
      isFirstLogin: false,
      state: 'मध्यप्रदेश',
      district: 'भिंड',
      currentAddress: 'Station Road, Bhind, MP',
      ancestralVillage: 'sirsod-सिरसोद',
      education: 'M.Com.',
      profession: 'व्यापार',
      gotra: 'mudgal-मुद्गल', // Same as Anjali
      motherGotra: 'gautam-गौतम', // Same as Rahul's mother gotra
      yearlyIncome: '5-10 लाख',
    },
    {
      mobile: '9876543231',
      email: 'swati.parashar@matrimonial.com',
      password: await bcrypt.hash('password123', 10),
      firstName: 'Swati',
      lastName: 'Pandey',
      fatherOrHusbandName: 'Dinesh Pandey',
      motherName: 'Usha Devi',
      maritalStatus: 'UNMARRIED',
      age: 25,
      dateOfBirth: new Date('2000-02-14'),
      gender: 'Female',
      role: 'USER',
      approvalStatus: 'APPROVED',
      isFirstLogin: false,
      state: 'मध्यप्रदेश',
      district: 'ग्वालियर',
      currentAddress: 'Jayendraganj, Gwalior, MP',
      ancestralVillage: 'khaneta-खानेटा',
      education: 'M.A.',
      profession: 'शिक्षण कार्य',
      gotra: 'parashar-पाराशर', // Same as Vikram
      motherGotra: 'bharadwaj-भारद्वाज', // Same as Priya's mother gotra
      yearlyIncome: '2-5 लाख',
    },
    {
      mobile: '9876543232',
      email: 'karan.gautam@matrimonial.com',
      password: await bcrypt.hash('password123', 10),
      firstName: 'Karan',
      lastName: 'Saxena',
      fatherOrHusbandName: 'Prakash Saxena',
      motherName: 'Rani Devi',
      maritalStatus: 'UNMARRIED',
      age: 31,
      dateOfBirth: new Date('1994-09-22'),
      gender: 'Male',
      role: 'USER',
      approvalStatus: 'APPROVED',
      isFirstLogin: false,
      state: 'उत्तरप्रदेश',
      district: 'मथुरा',
      currentAddress: 'Vrindavan, Mathura, UP',
      ancestralVillage: 'govardhan-गोवर्धन',
      education: 'B.E.',
      profession: 'शासकीय सेवा',
      gotra: 'gautam-गौतम', // Same as Priya and Amit
      motherGotra: 'chaube-चौबे',
      yearlyIncome: '5-10 लाख',
    },
    {
      mobile: '9876543233',
      email: 'nisha.mudgal@matrimonial.com',
      password: await bcrypt.hash('password123', 10),
      firstName: 'Nisha',
      lastName: 'Agarwal',
      fatherOrHusbandName: 'Vinod Agarwal',
      motherName: 'Meena Devi',
      maritalStatus: 'UNMARRIED',
      age: 27,
      dateOfBirth: new Date('1998-06-30'),
      gender: 'Female',
      role: 'USER',
      approvalStatus: 'APPROVED',
      isFirstLogin: false,
      state: 'मध्यप्रदेश',
      district: 'मुरैना',
      currentAddress: 'Collectorate Area, Morena, MP',
      ancestralVillage: 'joura-जौरा',
      education: 'B.Com.',
      profession: 'लेखा कार्य',
      gotra: 'mudgal-मुद्गल', // Same as Anjali and Vivek
      motherGotra: 'parashar-पाराशर',
      yearlyIncome: '2-5 लाख',
    },
    {
      mobile: '9876543234',
      email: 'rohit.bharadwaj2@matrimonial.com',
      password: await bcrypt.hash('password123', 10),
      firstName: 'Rohit',
      lastName: 'Pathak',
      fatherOrHusbandName: 'Anil Pathak',
      motherName: 'Kiran Devi',
      maritalStatus: 'UNMARRIED',
      age: 26,
      dateOfBirth: new Date('1999-12-08'),
      gender: 'Male',
      role: 'USER',
      approvalStatus: 'APPROVED',
      isFirstLogin: false,
      state: 'उत्तरप्रदेश',
      district: 'आगरा',
      currentAddress: 'Dayal Bagh, Agra, UP',
      ancestralVillage: 'etmadpur-एटमादपुर',
      education: 'B.Tech',
      profession: 'इंजीनियरिंग कार्य',
      gotra: 'bharadwaj-भारद्वाज', // Same as Rahul and Ritu
      motherGotra: 'mudgal-मुद्गल',
      yearlyIncome: '5-10 लाख',
    },
    {
      mobile: '9876543235',
      email: 'priti.chaube@matrimonial.com',
      password: await bcrypt.hash('password123', 10),
      firstName: 'Priti',
      lastName: 'Joshi',
      fatherOrHusbandName: 'Manoj Joshi',
      motherName: 'Pushpa Devi',
      maritalStatus: 'UNMARRIED',
      age: 23,
      dateOfBirth: new Date('2002-04-17'),
      gender: 'Female',
      role: 'USER',
      approvalStatus: 'APPROVED',
      isFirstLogin: false,
      state: 'मध्यप्रदेश',
      district: 'भिंड',
      currentAddress: 'Gopal Ganj, Bhind, MP',
      ancestralVillage: 'mihona-मिहोना',
      education: 'B.A.',
      profession: 'गृह कार्य',
      gotra: 'chaube-चौबे', // Same as Arjun
      motherGotra: 'gautam-गौतम', // Same as Rahul's mother gotra
      yearlyIncome: '1-2 लाख',
    },
    {
      mobile: '9876543236',
      email: 'manish.parashar@matrimonial.com',
      password: await bcrypt.hash('password123', 10),
      firstName: 'Manish',
      lastName: 'Tripathi',
      fatherOrHusbandName: 'Shyam Tripathi',
      motherName: 'Rita Devi',
      maritalStatus: 'UNMARRIED',
      age: 32,
      dateOfBirth: new Date('1993-07-11'),
      gender: 'Male',
      role: 'USER',
      approvalStatus: 'APPROVED',
      isFirstLogin: false,
      state: 'मध्यप्रदेश',
      district: 'ग्वालियर',
      currentAddress: 'City Center, Gwalior, MP',
      ancestralVillage: 'dabra-डबरा',
      education: 'MBA',
      profession: 'प्रबंधन कार्य',
      gotra: 'parashar-पाराशर', // Same as Vikram and Swati
      motherGotra: 'bharadwaj-भारद्वाज',
      yearlyIncome: '10+ लाख',
    },
    {
      mobile: '9876543237',
      email: 'divya.gautam2@matrimonial.com',
      password: await bcrypt.hash('password123', 10),
      firstName: 'Divya',
      lastName: 'Srivastava',
      fatherOrHusbandName: 'Rajiv Srivastava',
      motherName: 'Anita Devi',
      maritalStatus: 'UNMARRIED',
      age: 24,
      dateOfBirth: new Date('2001-10-25'),
      gender: 'Female',
      role: 'USER',
      approvalStatus: 'APPROVED',
      isFirstLogin: false,
      state: 'उत्तरप्रदेश',
      district: 'मथुरा',
      currentAddress: 'Krishna Nagar, Mathura, UP',
      ancestralVillage: 'baldeo-बलदेव',
      education: '12वीं',
      profession: 'गृह कार्य',
      gotra: 'gautam-गौतम', // Same as Priya, Amit, Karan
      motherGotra: 'parashar-पाराशर',
      yearlyIncome: '1-2 लाख',
    },
    {
      mobile: '9876543238',
      email: 'sunil.chaube@matrimonial.com',
      password: await bcrypt.hash('password123', 10),
      firstName: 'Sunil',
      lastName: 'Dwivedi',
      fatherOrHusbandName: 'Hari Dwivedi',
      motherName: 'Sushila Devi',
      maritalStatus: 'UNMARRIED',
      age: 28,
      dateOfBirth: new Date('1997-03-19'),
      gender: 'Male',
      role: 'USER',
      approvalStatus: 'APPROVED',
      isFirstLogin: false,
      state: 'मध्यप्रदेश',
      district: 'भिंड',
      currentAddress: 'New Colony, Bhind, MP',
      ancestralVillage: 'basai-बसई',
      education: 'B.Sc.',
      profession: 'कृषि कार्य',
      gotra: 'chaube-चौबे', // Same as Arjun and Priti
      motherGotra: 'mudgal-मुद्गल',
      yearlyIncome: '2-5 लाख',
    },
    {
      mobile: '9876543239',
      email: 'kavita.bharadwaj@matrimonial.com',
      password: await bcrypt.hash('password123', 10),
      firstName: 'Kavita',
      lastName: 'Yadav',
      fatherOrHusbandName: 'Devendra Yadav',
      motherName: 'Sunita Devi',
      maritalStatus: 'UNMARRIED',
      age: 26,
      dateOfBirth: new Date('1999-01-12'),
      gender: 'Female',
      role: 'USER',
      approvalStatus: 'APPROVED',
      isFirstLogin: false,
      state: 'उत्तरप्रदेश',
      district: 'आगरा',
      currentAddress: 'Kamla Nagar, Agra, UP',
      ancestralVillage: 'runkata-रुनकता',
      education: 'M.A.',
      profession: 'शिक्षण कार्य',
      gotra: 'bharadwaj-भारद्वाज', // Same as Rahul, Ritu, Rohit
      motherGotra: 'gautam-गौतम',
      yearlyIncome: '2-5 लाख',
    },
    {
      mobile: '9876543240',
      email: 'alok.mudgal2@matrimonial.com',
      password: await bcrypt.hash('password123', 10),
      firstName: 'Alok',
      lastName: 'Singh',
      fatherOrHusbandName: 'Vijay Singh',
      motherName: 'Poonam Devi',
      maritalStatus: 'UNMARRIED',
      age: 29,
      dateOfBirth: new Date('1996-08-07'),
      gender: 'Male',
      role: 'USER',
      approvalStatus: 'APPROVED',
      isFirstLogin: false,
      state: 'मध्यप्रदेश',
      district: 'मुरैना',
      currentAddress: 'Ambah Road, Morena, MP',
      ancestralVillage: 'sabalgarh-सबलगढ़',
      education: 'B.Com.',
      profession: 'व्यापार',
      gotra: 'mudgal-मुद्गल', // Same as Anjali, Vivek, Nisha
      motherGotra: 'chaube-चौबे',
      yearlyIncome: '5-10 लाख',
    },
    {
      mobile: '9876543241',
      email: 'tanvi.parashar@matrimonial.com',
      password: await bcrypt.hash('password123', 10),
      firstName: 'Tanvi',
      lastName: 'Verma',
      fatherOrHusbandName: 'Ajay Verma',
      motherName: 'Nisha Devi',
      maritalStatus: 'UNMARRIED',
      age: 25,
      dateOfBirth: new Date('2000-05-20'),
      gender: 'Female',
      role: 'USER',
      approvalStatus: 'APPROVED',
      isFirstLogin: false,
      state: 'मध्यप्रदेश',
      district: 'ग्वालियर',
      currentAddress: 'Maharaj Bada, Gwalior, MP',
      ancestralVillage: 'pichhore-पिछोर',
      education: 'B.Tech',
      profession: 'इंजीनियरिंग कार्य',
      gotra: 'parashar-पाराशर', // Same as Vikram, Swati, Manish
      motherGotra: 'mudgal-मुद्गल',
      yearlyIncome: '5-10 लाख',
    },
    {
      mobile: '9876543242',
      email: 'pankaj.gautam3@matrimonial.com',
      password: await bcrypt.hash('password123', 10),
      firstName: 'Pankaj',
      lastName: 'Chaturvedi',
      fatherOrHusbandName: 'Mohan Chaturvedi',
      motherName: 'Radha Devi',
      maritalStatus: 'UNMARRIED',
      age: 30,
      dateOfBirth: new Date('1995-11-28'),
      gender: 'Male',
      role: 'USER',
      approvalStatus: 'APPROVED',
      isFirstLogin: false,
      state: 'उत्तरप्रदेश',
      district: 'मथुरा',
      currentAddress: 'Govind Nagar, Mathura, UP',
      ancestralVillage: 'chhata-छाता',
      education: 'M.Tech',
      profession: 'शासकीय सेवा',
      gotra: 'gautam-गौतम', // Same as Priya, Amit, Karan, Divya
      motherGotra: 'bharadwaj-भारद्वाज',
      yearlyIncome: '10+ लाख',
    },
    // Additional males with mother gotra भारद्वाज for testing partial match with Priya
    {
      mobile: '9876543243',
      email: 'deepak.chaube@matrimonial.com',
      password: await bcrypt.hash('password123', 10),
      firstName: 'Deepak',
      lastName: 'Shukla',
      fatherOrHusbandName: 'Ramesh Shukla',
      motherName: 'Bharti Devi',
      maritalStatus: 'UNMARRIED',
      age: 27,
      dateOfBirth: new Date('1998-06-15'),
      gender: 'Male',
      role: 'USER',
      approvalStatus: 'APPROVED',
      isFirstLogin: false,
      state: 'मध्यप्रदेश',
      district: 'भिंड',
      currentAddress: 'Pura Mohalla, Bhind, MP',
      ancestralVillage: 'amayan-अमायन',
      education: 'B.A.',
      profession: 'व्यापार',
      gotra: 'chaube-चौबे',
      motherGotra: 'bharadwaj-भारद्वाज', // Mother gotra matches Priya's mother gotra
      yearlyIncome: '2-5 लाख',
    },
    {
      mobile: '9876543244',
      email: 'rajat.vashishth@matrimonial.com',
      password: await bcrypt.hash('password123', 10),
      firstName: 'Rajat',
      lastName: 'Ojha',
      fatherOrHusbandName: 'Narendra Ojha',
      motherName: 'Suman Devi',
      maritalStatus: 'UNMARRIED',
      age: 29,
      dateOfBirth: new Date('1996-09-22'),
      gender: 'Male',
      role: 'USER',
      approvalStatus: 'APPROVED',
      isFirstLogin: false,
      state: 'उत्तरप्रदेश',
      district: 'आगरा',
      currentAddress: 'Tajganj, Agra, UP',
      ancestralVillage: 'fatehabad-फतेहाबाद',
      education: 'B.Tech',
      profession: 'इंजीनियरिंग कार्य',
      gotra: 'vashishth-वशिष्ठ',
      motherGotra: 'bharadwaj-भारद्वाज', // Mother gotra matches Priya's mother gotra
      yearlyIncome: '5-10 लाख',
    },
    {
      mobile: '9876543245',
      email: 'aditya.kashyap@matrimonial.com',
      password: await bcrypt.hash('password123', 10),
      firstName: 'Aditya',
      lastName: 'Mishra',
      fatherOrHusbandName: 'Krishna Mishra',
      motherName: 'Rekha Devi',
      maritalStatus: 'UNMARRIED',
      age: 26,
      dateOfBirth: new Date('1999-11-08'),
      gender: 'Male',
      role: 'USER',
      approvalStatus: 'APPROVED',
      isFirstLogin: false,
      state: 'मध्यप्रदेश',
      district: 'ग्वालियर',
      currentAddress: 'Thatipur, Gwalior, MP',
      ancestralVillage: 'bilaua-बिलावा',
      education: 'B.Com.',
      profession: 'लेखा कार्य',
      gotra: 'kashyap-काश्यप',
      motherGotra: 'bharadwaj-भारद्वाज', // Mother gotra matches Priya's mother gotra
      yearlyIncome: '2-5 लाख',
    },
    {
      mobile: '9876543246',
      email: 'vishal.shandilya@matrimonial.com',
      password: await bcrypt.hash('password123', 10),
      firstName: 'Vishal',
      lastName: 'Pandey',
      fatherOrHusbandName: 'Ashok Pandey',
      motherName: 'Manju Devi',
      maritalStatus: 'UNMARRIED',
      age: 31,
      dateOfBirth: new Date('1994-04-18'),
      gender: 'Male',
      role: 'USER',
      approvalStatus: 'APPROVED',
      isFirstLogin: false,
      state: 'उत्तरप्रदेश',
      district: 'मथुरा',
      currentAddress: 'Masani, Mathura, UP',
      ancestralVillage: 'sonkh-सोंख',
      education: 'MBA',
      profession: 'प्रबंधन कार्य',
      gotra: 'shandilya-शांडिल्य',
      motherGotra: 'bharadwaj-भारद्वाज', // Mother gotra matches Priya's mother gotra
      yearlyIncome: '10+ लाख',
    },
    {
      mobile: '9876543247',
      email: 'saurabh.kaushik@matrimonial.com',
      password: await bcrypt.hash('password123', 10),
      firstName: 'Saurabh',
      lastName: 'Tiwari',
      fatherOrHusbandName: 'Brijesh Tiwari',
      motherName: 'Kavita Devi',
      maritalStatus: 'UNMARRIED',
      age: 28,
      dateOfBirth: new Date('1997-07-25'),
      gender: 'Male',
      role: 'USER',
      approvalStatus: 'APPROVED',
      isFirstLogin: false,
      state: 'मध्यप्रदेश',
      district: 'भिंड',
      currentAddress: 'City Kotwali, Bhind, MP',
      ancestralVillage: 'seondha-सेवंधा',
      education: 'B.Sc.',
      profession: 'शासकीय सेवा',
      gotra: 'kaushik-कौशिक',
      motherGotra: 'bharadwaj-भारद्वाज', // Mother gotra matches Priya's mother gotra
      yearlyIncome: '5-10 लाख',
    },
    // Additional Moderators with assigned villages
    {
      mobile: '9876543248',
      email: 'moderator.akoda@matrimonial.com',
      password: await bcrypt.hash('password123', 10),
      firstName: 'Ramesh',
      lastName: 'Sharma',
      fatherOrHusbandName: 'Suresh Sharma',
      motherName: 'Geeta Devi',
      maritalStatus: 'MARRIED',
      age: 35,
      dateOfBirth: new Date('1990-03-15'),
      gender: 'Male',
      role: 'MODERATOR',
      approvalStatus: 'APPROVED',
      isFirstLogin: false,
      assignedVillage: 'akoda-अकोड़ा',
      state: 'मध्यप्रदेश',
      district: 'भिंड',
      currentAddress: 'Main Road, Bhind, MP',
      ancestralVillage: 'akoda-अकोड़ा',
      education: 'M.A.',
      profession: 'समाज सेवा',
      gotra: 'gautam-गौतम',
      motherGotra: 'mudgal-मुद्गल',
      yearlyIncome: '5-8 लाख',
    },
    {
      mobile: '9876543249',
      email: 'moderator.charathar@matrimonial.com',
      password: await bcrypt.hash('password123', 10),
      firstName: 'Sunita',
      lastName: 'Mishra',
      fatherOrHusbandName: 'Rakesh Mishra',
      motherName: 'Sushila Devi',
      maritalStatus: 'MARRIED',
      age: 33,
      dateOfBirth: new Date('1992-07-20'),
      gender: 'Female',
      role: 'MODERATOR',
      approvalStatus: 'APPROVED',
      isFirstLogin: false,
      assignedVillage: 'charathar-चरथर',
      state: 'मध्यप्रदेश',
      district: 'ग्वालियर',
      currentAddress: 'City Center, Gwalior, MP',
      ancestralVillage: 'charathar-चरथर',
      education: 'B.Ed.',
      profession: 'शिक्षण कार्य',
      gotra: 'bharadwaj-भारद्वाज',
      motherGotra: 'parashar-पाराशर',
      yearlyIncome: '4-6 लाख',
    },
    {
      mobile: '9876543250',
      email: 'moderator.sirsod@matrimonial.com',
      password: await bcrypt.hash('password123', 10),
      firstName: 'Manoj',
      lastName: 'Tiwari',
      fatherOrHusbandName: 'Kamal Tiwari',
      motherName: 'Poonam Devi',
      maritalStatus: 'MARRIED',
      age: 38,
      dateOfBirth: new Date('1987-11-10'),
      gender: 'Male',
      role: 'MODERATOR',
      approvalStatus: 'APPROVED',
      isFirstLogin: false,
      assignedVillage: 'sirsod-सिरसोद',
      state: 'मध्यप्रदेश',
      district: 'भिंड',
      currentAddress: 'Station Road, Bhind, MP',
      ancestralVillage: 'sirsod-सिरसोद',
      education: 'M.Com.',
      profession: 'समाज सेवा',
      gotra: 'mudgal-मुद्गल',
      motherGotra: 'chaube-चौबे',
      yearlyIncome: '6-9 लाख',
    },
    // Pending users from akoda village
    {
      mobile: '9876543251',
      email: 'pending.akoda1@matrimonial.com',
      password: await bcrypt.hash('password123', 10),
      firstName: 'Pooja',
      lastName: 'Verma',
      fatherOrHusbandName: 'Ashok Verma',
      motherName: 'Rekha Devi',
      maritalStatus: 'UNMARRIED',
      age: 24,
      dateOfBirth: new Date('2001-05-12'),
      gender: 'Female',
      role: 'USER',
      approvalStatus: 'PENDING',
      isFirstLogin: false,
      state: 'मध्यप्रदेश',
      district: 'भिंड',
      currentAddress: 'Village Road, Bhind, MP',
      ancestralVillage: 'akoda-अकोड़ा',
      education: 'B.A.',
      profession: 'गृह कार्य',
      gotra: 'parashar-पाराशर',
      motherGotra: 'gautam-गौतम',
      yearlyIncome: '1-2 लाख',
    },
    {
      mobile: '9876543252',
      email: 'pending.akoda2@matrimonial.com',
      password: await bcrypt.hash('password123', 10),
      firstName: 'Rajesh',
      lastName: 'Kumar',
      fatherOrHusbandName: 'Ramesh Kumar',
      motherName: 'Meena Devi',
      maritalStatus: 'UNMARRIED',
      age: 27,
      dateOfBirth: new Date('1998-09-18'),
      gender: 'Male',
      role: 'USER',
      approvalStatus: 'PENDING',
      isFirstLogin: false,
      state: 'मध्यप्रदेश',
      district: 'भिंड',
      currentAddress: 'Near Temple, Bhind, MP',
      ancestralVillage: 'akoda-अकोड़ा',
      education: 'B.Com.',
      profession: 'व्यापार',
      gotra: 'chaube-चौबे',
      motherGotra: 'bharadwaj-भारद्वाज',
      yearlyIncome: '3-5 लाख',
    },
    {
      mobile: '9876543253',
      email: 'pending.akoda3@matrimonial.com',
      password: await bcrypt.hash('password123', 10),
      firstName: 'Sneha',
      lastName: 'Gupta',
      fatherOrHusbandName: 'Vinod Gupta',
      motherName: 'Anita Devi',
      maritalStatus: 'UNMARRIED',
      age: 23,
      dateOfBirth: new Date('2002-12-05'),
      gender: 'Female',
      role: 'USER',
      approvalStatus: 'PENDING',
      isFirstLogin: false,
      state: 'मध्यप्रदेश',
      district: 'भिंड',
      currentAddress: 'Main Bazaar, Bhind, MP',
      ancestralVillage: 'akoda-अकोड़ा',
      education: '12वीं',
      profession: 'गृह कार्य',
      gotra: 'mudgal-मुद्गल',
      motherGotra: 'parashar-पाराशर',
      yearlyIncome: '1-2 लाख',
    },
    // Pending users from charathar village
    {
      mobile: '9876543254',
      email: 'pending.charathar1@matrimonial.com',
      password: await bcrypt.hash('password123', 10),
      firstName: 'Amit',
      lastName: 'Pandey',
      fatherOrHusbandName: 'Mahesh Pandey',
      motherName: 'Savita Devi',
      maritalStatus: 'UNMARRIED',
      age: 26,
      dateOfBirth: new Date('1999-03-22'),
      gender: 'Male',
      role: 'USER',
      approvalStatus: 'PENDING',
      isFirstLogin: false,
      state: 'मध्यप्रदेश',
      district: 'ग्वालियर',
      currentAddress: 'Lashkar, Gwalior, MP',
      ancestralVillage: 'charathar-चरथर',
      education: 'B.Tech',
      profession: 'इंजीनियरिंग कार्य',
      gotra: 'vashishth-वशिष्ठ',
      motherGotra: 'mudgal-मुद्गल',
      yearlyIncome: '4-6 लाख',
    },
    {
      mobile: '9876543255',
      email: 'pending.charathar2@matrimonial.com',
      password: await bcrypt.hash('password123', 10),
      firstName: 'Neha',
      lastName: 'Singh',
      fatherOrHusbandName: 'Rajeev Singh',
      motherName: 'Kiran Devi',
      maritalStatus: 'UNMARRIED',
      age: 25,
      dateOfBirth: new Date('2000-08-14'),
      gender: 'Female',
      role: 'USER',
      approvalStatus: 'PENDING',
      isFirstLogin: false,
      state: 'मध्यप्रदेश',
      district: 'ग्वालियर',
      currentAddress: 'Thatipur, Gwalior, MP',
      ancestralVillage: 'charathar-चरथर',
      education: 'M.A.',
      profession: 'शिक्षण कार्य',
      gotra: 'kashyap-काश्यप',
      motherGotra: 'bharadwaj-भारद्वाज',
      yearlyIncome: '3-5 लाख',
    },
    // Pending users from sirsod village
    {
      mobile: '9876543256',
      email: 'pending.sirsod1@matrimonial.com',
      password: await bcrypt.hash('password123', 10),
      firstName: 'Vikas',
      lastName: 'Dubey',
      fatherOrHusbandName: 'Pankaj Dubey',
      motherName: 'Usha Devi',
      maritalStatus: 'UNMARRIED',
      age: 28,
      dateOfBirth: new Date('1997-06-30'),
      gender: 'Male',
      role: 'USER',
      approvalStatus: 'PENDING',
      isFirstLogin: false,
      state: 'मध्यप्रदेश',
      district: 'भिंड',
      currentAddress: 'Colony Area, Bhind, MP',
      ancestralVillage: 'sirsod-सिरसोद',
      education: 'B.Sc.',
      profession: 'कृषि कार्य',
      gotra: 'shandilya-शांडिल्य',
      motherGotra: 'gautam-गौतम',
      yearlyIncome: '2-4 लाख',
    },
    {
      mobile: '9876543257',
      email: 'pending.sirsod2@matrimonial.com',
      password: await bcrypt.hash('password123', 10),
      firstName: 'Ritu',
      lastName: 'Agarwal',
      fatherOrHusbandName: 'Sanjay Agarwal',
      motherName: 'Nisha Devi',
      maritalStatus: 'UNMARRIED',
      age: 24,
      dateOfBirth: new Date('2001-10-08'),
      gender: 'Female',
      role: 'USER',
      approvalStatus: 'PENDING',
      isFirstLogin: false,
      state: 'मध्यप्रदेश',
      district: 'भिंड',
      currentAddress: 'Purana Bazaar, Bhind, MP',
      ancestralVillage: 'sirsod-सिरसोद',
      education: 'B.Com.',
      profession: 'लेखा कार्य',
      gotra: 'parashar-पाराशर',
      motherGotra: 'chaube-चौबे',
      yearlyIncome: '2-3 लाख',
    },
  ]

  for (const userData of dummyUsers) {
    await prisma.user.upsert({
      where: { mobile: userData.mobile },
      update: {},
      create: userData,
    })
  }

  console.log('\n✅ Created 57 dummy users:')
  console.log('   - 48 regular users (40 approved, 8 pending)')
  console.log('   - 5 moderators (approved) with assigned villages')
  console.log('   - 1 admin (you)')
  console.log('\n📍 Moderators by Village:')
  console.log('   - अकोड़ा (akoda): Ramesh Sharma - 9876543248')
  console.log('   - चरथर (charathar): Sunita Mishra - 9876543249')
  console.log('   - सिरसोद (sirsod): Manoj Tiwari - 9876543250')
  console.log('   - विर्धनपुरा (virdhanpura): Vikram Singh - 9876543213')
  console.log('   - पाली (pali): Kavita Sharma - 9876543216')
  console.log('\n📝 Pending Users by Village:')
  console.log('   - अकोड़ा: 3 pending users')
  console.log('   - चरथर: 2 pending users')
  console.log('   - सिरसोद: 2 pending users')
  console.log('\n📝 All dummy accounts use password: password123')
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
